export const dynamic = "force-dynamic";
export const maxDuration = 60;

import { NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import { prisma } from "@/lib/prisma";

// ─────────────────────────────────────────────────────────────────────────────
// The Roundtable — podcast-style pregame conversation (owner request 7/17).
// Four fixed personas; the script is generated by Claude Sonnet, grounded in
// DB squads + real results. Audio comes line-by-line from /api/ai/tts with the
// persona key (server-side voice mapping). Cached in memory per fixture (6h) —
// one Sonnet call (~$0.03) serves everyone until regen.
// ─────────────────────────────────────────────────────────────────────────────

export interface RoundtableLine {
  speaker: "lorraine" | "henry" | "roberto" | "ricky";
  text: string;
}
export interface Roundtable {
  fixture: number;
  title: string;
  matchup: string;
  lines: RoundtableLine[];
  generatedAt: string;
}

const SPEAKERS: Record<RoundtableLine["speaker"], { name: string; role: string }> = {
  lorraine: { name: "Lorraine Footy",  role: "Host · Britain" },
  henry:    { name: "Henry Futois",    role: "French ex-pro · flair & tactics" },
  roberto:  { name: "Roberto Madrid",  role: "Spanish ex-goalkeeper" },
  ricky:    { name: "Ricky Riquelme",  role: "Argentinian legend · old school" },
};

let _cache = new Map<number, { ts: number; data: Roundtable }>();
const TTL = 6 * 60 * 60 * 1000; // 6h

async function buildGrounding(fixture: number): Promise<{ matchup: string; context: string } | null> {
  const match = await prisma.match.findFirst({
    where: { fixture },
    include: { homeTeam: true, awayTeam: true },
  });
  if (!match) return null;

  const [homeSquad, awaySquad, recent] = await Promise.all([
    prisma.player.findMany({ where: { teamId: match.homeTeamId }, orderBy: { number: "asc" } }),
    prisma.player.findMany({ where: { teamId: match.awayTeamId }, orderBy: { number: "asc" } }),
    prisma.match.findMany({
      where: {
        status: "FT",
        OR: [
          { homeTeamId: { in: [match.homeTeamId, match.awayTeamId] } },
          { awayTeamId: { in: [match.homeTeamId, match.awayTeamId] } },
        ],
      },
      include: { homeTeam: true, awayTeam: true },
      orderBy: { date: "desc" },
      take: 12,
    }),
  ]);

  const squadLines = (label: string, squad: typeof homeSquad) =>
    squad.length
      ? `${label} SQUAD (from our database — the ONLY players you may name for this team):\n` +
        squad.map((p) => `#${p.number} ${p.name} — ${p.position}${p.club ? `, ${p.club}` : ""}${p.caps ? `, ${p.caps} caps` : ""}${p.goals ? `, ${p.goals} international goals` : ""}`).join("\n")
      : `${label} SQUAD: not in database — do NOT name any ${label} players.`;

  const resultLines = recent
    .map((m) => `${new Date(m.date).toISOString().slice(0, 10)}: ${m.homeTeam.name} ${m.homeScore}-${m.awayScore} ${m.awayTeam.name}`)
    .join("\n");

  const kickoff = new Date(match.date).toUTCString();

  return {
    matchup: `${match.homeTeam.name} v ${match.awayTeam.name}`,
    context: [
      `FIXTURE: ${match.homeTeam.name} v ${match.awayTeam.name} — ${kickoff} at ${match.venue}${match.city ? `, ${match.city}` : ""}.`,
      squadLines(match.homeTeam.name, homeSquad),
      squadLines(match.awayTeam.name, awaySquad),
      `RECENT TOURNAMENT RESULTS (both teams):\n${resultLines || "none recorded"}`,
    ].join("\n\n"),
  };
}

async function generate(fixture: number): Promise<Roundtable | null> {
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) return null;
  const grounding = await buildGrounding(fixture);
  if (!grounding) return null;

  const client = new Anthropic({ apiKey: key });
  const msg = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 3000,
    system: `You write a pregame football roundtable podcast script for four FIXED fictional personas — the owner's cast (7/18):
- lorraine — Lorraine Footy, the warm, sharp BRITISH host. Steers topics, teases the panel with dry British wit. English only ("right then", "come on now").
- henry — Henry Futois, FRENCH former PSG player. Flair, tactics, artistry — believes football is beautiful or it is nothing. Sprinkles French: "écoutez", "voilà", "magnifique", "non non non" (a phrase or two per line MAX, meaning always clear).
- roberto — Roberto Madrid, SPANISH former Real Madrid goalkeeper. THE authority on goalkeeping and defending — reads the game from the back. Castilian sprinkles: "vale", "madre mía", "qué barbaridad", "tranquilo".
- ricky — Ricky Riquelme, ARGENTINIAN legend, an old man who played for Boca Juniors. Old-school passion, storytelling grandpa energy, heart bleeding sky-blue-and-white for this one: "che", "dale", "vamos", "en mis tiempos" (in my day).
Persona-backstory rule: they may color commentary with VAGUE nostalgia ("in my playing days", "as a keeper I hated this") but must NEVER invent specific career matches, opponents, teammates, dates, or statistics for themselves.
Code-switch rule for all: foreign phrases are seasoning, not the meal — every line must be fully understandable to an English-only listener.

HARD GROUNDING RULES (violations are publication errors):
- Name ONLY players listed in the squads below. Never invent players, transfers, injuries, quotes, or fitness news.
- Cite ONLY statistics present in the provided data. No invented stats, odds, or historical scorelines.
- Career-legacy talk about globally famous players (e.g. an all-time-great debate) may reference well-established career facts qualitatively ("multiple World Cups", "a career of trophies") but NO specific invented numbers.
- Projected lineups must be drawn from the listed squad and framed as "my guess" / "I'd go with", never as confirmed team news.
- Tactics talk is speculation and must sound like opinion ("I think", "watch for", "if I'm the manager").
- Refer to the competition as "the tournament" or "the final". Never claim official status.

FORMAT: Return ONLY valid JSON: {"title": string, "lines": [{"speaker": "lorraine"|"henry"|"roberto"|"ricky", "text": string}]}.
16-22 lines total. Lorraine opens and closes. Every voice appears at least 3 times. Each line 1-3 sentences, natural spoken cadence — this becomes audio.

WRITE FOR PERFORMANCE — these lines are spoken aloud by TTS voices:
- Punch it up: exclamation marks where the emotion is real, em-dashes for dramatic beats, rhetorical questions, short sentences that LAND.
- One ALL-CAPS word per big moment is allowed for emphasis ("that save was ENORMOUS") — never more.
- The panel reacts to each other by name, interrupts with energy, disagrees loudly, laughs in words ("ha!", "oh come on").
- NEVER use stage directions, brackets, asterisks, or emoji — the voices will read them literally.
COVER, conversationally (not as a checklist): the goalkeeping matchup, the defensive battle, the legacy angle for any all-time-great on the pitch, both projected XIs with a bench name or two, and each manager's likely tactical plan.`,
    messages: [{ role: "user", content: `Tonight's episode covers this fixture. All usable data follows.\n\n${grounding.context}` }],
  });

  const raw = msg.content[0]?.type === "text" ? msg.content[0].text : "";
  const jsonStr = raw.slice(raw.indexOf("{"), raw.lastIndexOf("}") + 1);
  let parsed: { title?: string; lines?: RoundtableLine[] };
  try {
    parsed = JSON.parse(jsonStr);
  } catch {
    return null;
  }
  const valid = (parsed.lines ?? []).filter(
    (l) => l && typeof l.text === "string" && l.text.length > 0 && l.speaker in SPEAKERS
  );
  if (valid.length < 6) return null;

  return {
    fixture,
    title: parsed.title || `The Roundtable · ${grounding.matchup}`,
    matchup: grounding.matchup,
    lines: valid,
    generatedAt: new Date().toISOString(),
  };
}

export async function GET(req: Request) {
  const fixture = parseInt(new URL(req.url).searchParams.get("fixture") ?? "", 10);
  if (!fixture) return NextResponse.json({ error: "fixture required" }, { status: 400 });

  const cached = _cache.get(fixture);
  if (cached && Date.now() - cached.ts < TTL) {
    return NextResponse.json({ roundtable: cached.data, cached: true });
  }

  try {
    const data = await generate(fixture);
    if (!data) {
      // Serve stale rather than nothing
      if (cached) return NextResponse.json({ roundtable: cached.data, cached: true, stale: true });
      return NextResponse.json({ roundtable: null }, { status: 503 });
    }
    _cache.set(fixture, { ts: Date.now(), data });
    return NextResponse.json({ roundtable: data, cached: false });
  } catch (e) {
    console.error("[roundtable]", e);
    if (cached) return NextResponse.json({ roundtable: cached.data, cached: true, stale: true });
    return NextResponse.json({ roundtable: null }, { status: 503 });
  }
}
