export const dynamic = "force-dynamic";
export const maxDuration = 60;

import { NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { getTeamTournamentProb } from "@/lib/polymarket";

// ─────────────────────────────────────────────────────────────────────────────
// The Roundtable — podcast-style pregame conversation (owner request 7/17).
// Four fixed personas; the script is generated by Claude Sonnet, grounded in
// DB squads + real results. Audio comes line-by-line from /api/ai/tts with the
// persona key (server-side voice mapping). Cached in memory per fixture (6h) —
// one Sonnet call (~$0.03) serves everyone until regen.
// ─────────────────────────────────────────────────────────────────────────────

export interface RoundtableLine {
  speaker: "lorraine" | "henry" | "roberto" | "ricky";
  text: string;
}
// The panel's gut-read intangibles (owner 7/18: the "IT" factors we all FEEL).
// Explicitly OPINION — feel is a 0-100 gut number from fictional pundits, never
// presented as a stat. Grounded rule still applies to the "why" text.
export interface ItRead {
  label: string; // e.g. "Hunger", "Big-game nerve"
  feel: number;  // 0-100 panel gut read
  why: string;   // one grounded sentence
}
export interface Roundtable {
  fixture: number;
  title: string;
  matchup: string;
  lines: RoundtableLine[];
  itFactor?: { home: ItRead[]; away: ItRead[] } | null;
  generatedAt: string;
}

// Bump when the script brief changes — pre-kickoff episodes regenerate so the
// new coverage (tale-of-the-tape, market read, IT factors) reaches today's
// game. Episodes already frozen at kickoff keep their archive copy.
const PROMPT_REV = "v2";

const SPEAKERS: Record<RoundtableLine["speaker"], { name: string; role: string }> = {
  lorraine: { name: "Lorraine Footy",  role: "Host · Britain" },
  henry:    { name: "Henry Futois",    role: "French ex-pro · flair & tactics" },
  roberto:  { name: "Roberto Madrid",  role: "Spanish ex-goalkeeper" },
  ricky:    { name: "Ricky Riquelme",  role: "Argentinian legend · old school" },
};

let _cache = new Map<number, { ts: number; data: Roundtable }>();
const TTL = 6 * 60 * 60 * 1000; // 6h

async function buildGrounding(fixture: number): Promise<{ matchup: string; context: string } | null> {
  const match = await prisma.match.findFirst({
    where: { fixture },
    include: { homeTeam: true, awayTeam: true },
  });
  if (!match) return null;

  const [homeSquad, awaySquad, recent] = await Promise.all([
    prisma.player.findMany({ where: { teamId: match.homeTeamId }, orderBy: { number: "asc" } }),
    prisma.player.findMany({ where: { teamId: match.awayTeamId }, orderBy: { number: "asc" } }),
    prisma.match.findMany({
      where: {
        status: "FT",
        OR: [
          { homeTeamId: { in: [match.homeTeamId, match.awayTeamId] } },
          { awayTeamId: { in: [match.homeTeamId, match.awayTeamId] } },
        ],
      },
      include: { homeTeam: true, awayTeam: true },
      orderBy: { date: "desc" },
      // Entire tournament for both teams (≤8 games each) — the aggregates
      // below must cover every game, not a recency window.
      take: 30,
    }),
  ]);

  const squadLines = (label: string, squad: typeof homeSquad) =>
    squad.length
      ? `${label} SQUAD (from our database — the ONLY players you may name for this team):\n` +
        squad.map((p) => `#${p.number} ${p.name} — ${p.position}${p.club ? `, ${p.club}` : ""}${p.caps ? `, ${p.caps} caps` : ""}${p.goals ? `, ${p.goals} international goals` : ""}`).join("\n")
      : `${label} SQUAD: not in database — do NOT name any ${label} players.`;

  const resultLines = recent
    .map((m) => `${new Date(m.date).toISOString().slice(0, 10)}: ${m.homeTeam.name} ${m.homeScore}-${m.awayScore} ${m.awayTeam.name}`)
    .join("\n");

  // Side-by-side tournament aggregates (matchday special, owner 7/18) — pure
  // arithmetic over the real FT results above, computed per team.
  const aggFor = (teamId: string, name: string) => {
    const played = recent.filter((m) => m.homeTeamId === teamId || m.awayTeamId === teamId);
    let w = 0, d = 0, l = 0, gf = 0, ga = 0, cs = 0;
    for (const m of played) {
      const isHome = m.homeTeamId === teamId;
      const f = (isHome ? m.homeScore : m.awayScore) ?? 0;
      const a = (isHome ? m.awayScore : m.homeScore) ?? 0;
      gf += f; ga += a;
      if (a === 0) cs++;
      if (f > a) w++; else if (f === a) d++; else l++;
    }
    return `${name}: P${played.length} W${w} D${d} L${l} · ${gf} scored, ${ga} conceded · ${cs} clean sheets`;
  };

  // Prediction-market context (Polymarket) — optional; both teams may be
  // absent from the tournament-winner market (e.g. the 3rd-place game).
  let marketLine = "";
  try {
    const [pHome, pAway] = await Promise.all([
      getTeamTournamentProb(match.homeTeam.code),
      getTeamTournamentProb(match.awayTeam.code),
    ]);
    const parts: string[] = [];
    if (pHome !== null) parts.push(`${match.homeTeam.name} ${(pHome * 100).toFixed(0)}%`);
    if (pAway !== null) parts.push(`${match.awayTeam.name} ${(pAway * 100).toFixed(0)}%`);
    if (parts.length) marketLine = `PREDICTION MARKET (Polymarket, tournament-winner probability): ${parts.join(" · ")}`;
  } catch { /* market data optional */ }

  const kickoff = new Date(match.date).toUTCString();

  return {
    matchup: `${match.homeTeam.name} v ${match.awayTeam.name}`,
    context: [
      `FIXTURE: ${match.homeTeam.name} v ${match.awayTeam.name} — ${kickoff} at ${match.venue}${match.city ? `, ${match.city}` : ""}.`,
      `TOURNAMENT TALE OF THE TAPE (from our database — the only aggregate numbers you may cite):\n${aggFor(match.homeTeamId, match.homeTeam.name)}\n${aggFor(match.awayTeamId, match.awayTeam.name)}`,
      marketLine,
      squadLines(match.homeTeam.name, homeSquad),
      squadLines(match.awayTeam.name, awaySquad),
      `RECENT TOURNAMENT RESULTS (both teams):\n${resultLines || "none recorded"}`,
    ].filter(Boolean).join("\n\n"),
  };
}

async function generate(fixture: number): Promise<Roundtable | null> {
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) return null;
  const grounding = await buildGrounding(fixture);
  if (!grounding) return null;

  const client = new Anthropic({ apiKey: key });
  const msg = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 3000,
    system: `You write a pregame football roundtable podcast script for four FIXED fictional personas — the owner's cast, written to match their VOICE designs (7/18):
- lorraine — Lorraine Footy, middle-aged BRITISH host in the classic football-commentary tradition — EXCITED by every aspect of the game, brilliant at banter, volleys the panel's chaos back at them with glee ("right then", "oh that's marvelous", "come on now").
- henry — Henry Futois, FRENCH former PSG and France player. Deep, gravelly, theatrical — menacing one second, absurdly silly the next, quick erratic bursts of maniacal energy. Flair-worshipper: football is art or it is nothing. French sprinkles: "écoutez", "voilà", "magnifique", "non non non".
- roberto — Roberto Madrid, SPANISH former Real Madrid and Spain goalkeeper, a massive man in his 30s. Smooth and rhythmic but absurdly silly, quick excited pace, erratic maniacal energy, big laughter, sharp sarcasm. THE authority on goalkeeping and defending. Catalan-accented sprinkles: "vale", "escolta", "madre mía", "qué barbaridad".
- ricky — Ricky Riquelme, ARGENTINIAN old man, former Boca Juniors and Argentina player. Booming, smooth, theatrical, eloquent — medium pace with bursts of excitement, big laughs, and HEAVY dry sarcasm. Storytelling grandpa whose heart bleeds sky-blue-and-white: "che", "dale", "vamos", "en mis tiempos".
The panel's comedy: Lorraine keeps order she secretly loves losing; Henry and Roberto feed each other's chaos; Ricky deadpans over the top of everyone and then erupts.
Persona-backstory rule: they may color commentary with VAGUE nostalgia ("in my playing days", "as a keeper I hated this") but must NEVER invent specific career matches, opponents, teammates, dates, or statistics for themselves.
Code-switch rule for all: foreign phrases are seasoning, not the meal — every line must be fully understandable to an English-only listener.

HARD GROUNDING RULES (violations are publication errors):
- Name ONLY players listed in the squads below. Never invent players, transfers, injuries, quotes, or fitness news.
- Cite ONLY statistics present in the provided data. No invented stats, odds, or historical scorelines.
- Career-legacy talk about globally famous players (e.g. an all-time-great debate) may reference well-established career facts qualitatively ("multiple World Cups", "a career of trophies") but NO specific invented numbers.
- Projected lineups must be drawn from the listed squad and framed as "my guess" / "I'd go with", never as confirmed team news.
- Tactics talk is speculation and must sound like opinion ("I think", "watch for", "if I'm the manager").
- Refer to the competition as "the tournament" or "the final". Never claim official status.

FORMAT: Return ONLY valid JSON:
{"title": string,
 "lines": [{"speaker": "lorraine"|"henry"|"roberto"|"ricky", "text": string}],
 "itFactor": {"home": [{"label": string, "feel": number, "why": string}], "away": [...]}}
16-22 lines total. Lorraine opens and closes. Every voice appears at least 3 times. Each line 1-3 sentences, natural spoken cadence — this becomes audio.
itFactor: exactly 3 reads per team — the INTANGIBLES the panel FEELS (hunger, big-game nerve, momentum, pride, redemption…). "feel" is a 0-100 gut number that is pure panel opinion (the UI labels it as such); "label" is 1-3 words; "why" is ONE sentence grounded in the provided results/context, no invented facts.

WRITE FOR PERFORMANCE — these lines are spoken aloud by TTS voices:
- Punch it up: exclamation marks where the emotion is real, em-dashes for dramatic beats, rhetorical questions, short sentences that LAND.
- One ALL-CAPS word per big moment is allowed for emphasis ("that save was ENORMOUS") — never more.
- The panel reacts to each other by name, interrupts with energy, disagrees loudly, laughs in words ("ha!", "oh come on").
- NEVER use stage directions, brackets, asterisks, or emoji — the voices will read them literally.
COVER, conversationally (not as a checklist): the TALE OF THE TAPE — walk the side-by-side tournament numbers and argue about what they mean; the market read if prediction-market data is provided (what the money thinks vs what the panel feels — frame market numbers as "the markets say"); the goalkeeping matchup; the defensive battle; the legacy angle for any all-time-great on the pitch; both projected XIs with a bench name or two; each manager's likely plan; and the IT FACTORS — the unmeasurable things everyone FEELS (hunger, nerve, destiny, wounded pride), each panelist championing what their gut says, clearly as feeling not fact.
MAKE IT EMOTIONAL: give each team its own emotional arc — what this game MEANS to that nation, its fans, its veterans — grounded in the real results provided (a semifinal exit is heartbreak; a title chance is history calling). The listener should feel their pulse rise for BOTH teams.`,
    messages: [{ role: "user", content: `Tonight's episode covers this fixture. All usable data follows.\n\n${grounding.context}` }],
  });

  const raw = msg.content[0]?.type === "text" ? msg.content[0].text : "";
  const jsonStr = raw.slice(raw.indexOf("{"), raw.lastIndexOf("}") + 1);
  let parsed: { title?: string; lines?: RoundtableLine[]; itFactor?: { home?: ItRead[]; away?: ItRead[] } };
  try {
    parsed = JSON.parse(jsonStr);
  } catch {
    return null;
  }
  const valid = (parsed.lines ?? []).filter(
    (l) => l && typeof l.text === "string" && l.text.length > 0 && l.speaker in SPEAKERS
  );
  if (valid.length < 6) return null;

  const validReads = (reads?: ItRead[]): ItRead[] =>
    (reads ?? [])
      .filter((r) => r && typeof r.label === "string" && typeof r.why === "string" && typeof r.feel === "number")
      .map((r) => ({ label: r.label.slice(0, 30), feel: Math.max(0, Math.min(100, Math.round(r.feel))), why: r.why }))
      .slice(0, 3);
  const itHome = validReads(parsed.itFactor?.home);
  const itAway = validReads(parsed.itFactor?.away);

  return {
    fixture,
    title: parsed.title || `The Roundtable · ${grounding.matchup}`,
    matchup: grounding.matchup,
    lines: valid,
    itFactor: itHome.length && itAway.length ? { home: itHome, away: itAway } : null,
    generatedAt: new Date().toISOString(),
  };
}

export async function GET(req: Request) {
  const fixture = parseInt(new URL(req.url).searchParams.get("fixture") ?? "", 10);
  if (!fixture) return NextResponse.json({ error: "fixture required" }, { status: 400 });

  const cached = _cache.get(fixture);
  if (cached && Date.now() - cached.ts < TTL) {
    return NextResponse.json({ roundtable: cached.data, cached: true });
  }

  // ── Canonical episode lives in the DB (owner 7/18) ─────────────────────────
  // Memory caches are per serverless instance — different instances generated
  // DIFFERENT episodes for the same fixture, which broke the global TTS audio
  // cache (different text = different blob keys = cold audio for each variant)
  // and lost episodes on every deploy. The DB row is the single source: every
  // instance serves the same script, and episodes survive as the archive.
  let dbEpisode: Roundtable | null = null;
  let dbAge = Infinity;
  let dbRev = PROMPT_REV;
  try {
    const row = await prisma.roundtableEpisode.findUnique({ where: { fixture } });
    if (row) {
      dbEpisode = {
        fixture,
        title: row.title,
        matchup: row.matchup,
        lines: row.lines as unknown as RoundtableLine[],
        itFactor: (row.itFactor as unknown as Roundtable["itFactor"]) ?? null,
        generatedAt: row.generatedAt.toISOString(),
      };
      dbAge = Date.now() - row.generatedAt.getTime();
      dbRev = row.promptRev;
    }
  } catch { /* table may not exist until first deploy after schema push */ }

  // Fresh + current-brief episodes serve directly; an old-rev episode falls
  // through so the upgraded brief regenerates it (unless already frozen at
  // kickoff below — the archive copy always wins post-kickoff).
  if (dbEpisode && dbAge < TTL && dbRev === PROMPT_REV) {
    _cache.set(fixture, { ts: Date.now() - dbAge, data: dbEpisode });
    return NextResponse.json({ roundtable: dbEpisode, cached: true });
  }

  // Pregame content freezes at kickoff: an episode recorded before the match
  // is the canonical archive copy — never regenerate over it.
  if (dbEpisode) {
    try {
      const m = await prisma.match.findFirst({ where: { fixture }, select: { date: true } });
      if (m && m.date.getTime() <= Date.now()) {
        _cache.set(fixture, { ts: Date.now(), data: dbEpisode });
        return NextResponse.json({ roundtable: dbEpisode, cached: true });
      }
    } catch { /* fall through to regen */ }
  }

  try {
    const data = await generate(fixture);
    if (!data) {
      // Serve stale rather than nothing
      const stale = dbEpisode ?? cached?.data ?? null;
      if (stale) return NextResponse.json({ roundtable: stale, cached: true, stale: true });
      return NextResponse.json({ roundtable: null }, { status: 503 });
    }
    _cache.set(fixture, { ts: Date.now(), data });
    try {
      const lines = data.lines as unknown as Prisma.InputJsonValue;
      const itFactor: Prisma.InputJsonValue | typeof Prisma.JsonNull =
        data.itFactor ? (data.itFactor as unknown as Prisma.InputJsonValue) : Prisma.JsonNull;
      await prisma.roundtableEpisode.upsert({
        where: { fixture },
        update: { title: data.title, matchup: data.matchup, lines, itFactor, promptRev: PROMPT_REV, generatedAt: new Date() },
        create: { fixture, title: data.title, matchup: data.matchup, lines, itFactor, promptRev: PROMPT_REV },
      });
    } catch { /* persistence is best-effort — the episode still serves */ }
    return NextResponse.json({ roundtable: data, cached: false });
  } catch (e) {
    console.error("[roundtable]", e);
    const stale = dbEpisode ?? cached?.data ?? null;
    if (stale) return NextResponse.json({ roundtable: stale, cached: true, stale: true });
    return NextResponse.json({ roundtable: null }, { status: 503 });
  }
}
