export const dynamic = "force-dynamic";
export const maxDuration = 60;

import { NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";

// ─────────────────────────────────────────────────────────────────────────────
// The Roundtable — podcast-style pregame conversation (owner request 7/17).
// Four fixed personas; the script is generated by Claude Sonnet, grounded in
// DB squads + real results. Audio comes line-by-line from /api/ai/tts with the
// persona key (server-side voice mapping). Cached in memory per fixture (6h) —
// one Sonnet call (~$0.03) serves everyone until regen.
// ─────────────────────────────────────────────────────────────────────────────

export interface RoundtableLine {
  speaker: "lorraine" | "henry" | "roberto" | "ricky";
  text: string;
}
export interface Roundtable {
  fixture: number;
  title: string;
  matchup: string;
  lines: RoundtableLine[];
  generatedAt: string;
}

const SPEAKERS: Record<RoundtableLine["speaker"], { name: string; role: string }> = {
  lorraine: { name: "Lorraine Footy",  role: "Host · Britain" },
  henry:    { name: "Henry Futois",    role: "French ex-pro · flair & tactics" },
  roberto:  { name: "Roberto Madrid",  role: "Spanish ex-goalkeeper" },
  ricky:    { name: "Ricky Riquelme",  role: "Argentinian legend · old school" },
};

let _cache = new Map<number, { ts: number; data: Roundtable }>();
const TTL = 6 * 60 * 60 * 1000; // 6h

async function buildGrounding(fixture: number): Promise<{ matchup: string; context: string } | null> {
  const match = await prisma.match.findFirst({
    where: { fixture },
    include: { homeTeam: true, awayTeam: true },
  });
  if (!match) return null;

  const [homeSquad, awaySquad, recent] = await Promise.all([
    prisma.player.findMany({ where: { teamId: match.homeTeamId }, orderBy: { number: "asc" } }),
    prisma.player.findMany({ where: { teamId: match.awayTeamId }, orderBy: { number: "asc" } }),
    prisma.match.findMany({
      where: {
        status: "FT",
        OR: [
          { homeTeamId: { in: [match.homeTeamId, match.awayTeamId] } },
          { awayTeamId: { in: [match.homeTeamId, match.awayTeamId] } },
        ],
      },
      include: { homeTeam: true, awayTeam: true },
      orderBy: { date: "desc" },
      take: 12,
    }),
  ]);

  const squadLines = (label: string, squad: typeof homeSquad) =>
    squad.length
      ? `${label} SQUAD (from our database — the ONLY players you may name for this team):\n` +
        squad.map((p) => `#${p.number} ${p.name} — ${p.position}${p.club ? `, ${p.club}` : ""}${p.caps ? `, ${p.caps} caps` : ""}${p.goals ? `, ${p.goals} international goals` : ""}`).join("\n")
      : `${label} SQUAD: not in database — do NOT name any ${label} players.`;

  const resultLines = recent
    .map((m) => `${new Date(m.date).toISOString().slice(0, 10)}: ${m.homeTeam.name} ${m.homeScore}-${m.awayScore} ${m.awayTeam.name}`)
    .join("\n");

  const kickoff = new Date(match.date).toUTCString();

  return {
    matchup: `${match.homeTeam.name} v ${match.awayTeam.name}`,
    context: [
      `FIXTURE: ${match.homeTeam.name} v ${match.awayTeam.name} — ${kickoff} at ${match.venue}${match.city ? `, ${match.city}` : ""}.`,
      squadLines(match.homeTeam.name, homeSquad),
      squadLines(match.awayTeam.name, awaySquad),
      `RECENT TOURNAMENT RESULTS (both teams):\n${resultLines || "none recorded"}`,
    ].join("\n\n"),
  };
}

async function generate(fixture: number): Promise<Roundtable | null> {
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) return null;
  const grounding = await buildGrounding(fixture);
  if (!grounding) return null;

  const client = new Anthropic({ apiKey: key });
  const msg = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 3000,
    system: `You write a pregame football roundtable podcast script for four FIXED fictional personas — the owner's cast, written to match their VOICE designs (7/18):
- lorraine — Lorraine Footy, middle-aged BRITISH host in the classic football-commentary tradition — EXCITED by every aspect of the game, brilliant at banter, volleys the panel's chaos back at them with glee ("right then", "oh that's marvelous", "come on now").
- henry — Henry Futois, FRENCH former PSG and France player. Deep, gravelly, theatrical — menacing one second, absurdly silly the next, quick erratic bursts of maniacal energy. Flair-worshipper: football is art or it is nothing. French sprinkles: "écoutez", "voilà", "magnifique", "non non non".
- roberto — Roberto Madrid, SPANISH former Real Madrid and Spain goalkeeper, a massive man in his 30s. Smooth and rhythmic but absurdly silly, quick excited pace, erratic maniacal energy, big laughter, sharp sarcasm. THE authority on goalkeeping and defending. Catalan-accented sprinkles: "vale", "escolta", "madre mía", "qué barbaridad".
- ricky — Ricky Riquelme, ARGENTINIAN old man, former Boca Juniors and Argentina player. Booming, smooth, theatrical, eloquent — medium pace with bursts of excitement, big laughs, and HEAVY dry sarcasm. Storytelling grandpa whose heart bleeds sky-blue-and-white: "che", "dale", "vamos", "en mis tiempos".
The panel's comedy: Lorraine keeps order she secretly loves losing; Henry and Roberto feed each other's chaos; Ricky deadpans over the top of everyone and then erupts.
Persona-backstory rule: they may color commentary with VAGUE nostalgia ("in my playing days", "as a keeper I hated this") but must NEVER invent specific career matches, opponents, teammates, dates, or statistics for themselves.
Code-switch rule for all: foreign phrases are seasoning, not the meal — every line must be fully understandable to an English-only listener.

HARD GROUNDING RULES (violations are publication errors):
- Name ONLY players listed in the squads below. Never invent players, transfers, injuries, quotes, or fitness news.
- Cite ONLY statistics present in the provided data. No invented stats, odds, or historical scorelines.
- Career-legacy talk about globally famous players (e.g. an all-time-great debate) may reference well-established career facts qualitatively ("multiple World Cups", "a career of trophies") but NO specific invented numbers.
- Projected lineups must be drawn from the listed squad and framed as "my guess" / "I'd go with", never as confirmed team news.
- Tactics talk is speculation and must sound like opinion ("I think", "watch for", "if I'm the manager").
- Refer to the competition as "the tournament" or "the final". Never claim official status.

FORMAT: Return ONLY valid JSON: {"title": string, "lines": [{"speaker": "lorraine"|"henry"|"roberto"|"ricky", "text": string}]}.
16-22 lines total. Lorraine opens and closes. Every voice appears at least 3 times. Each line 1-3 sentences, natural spoken cadence — this becomes audio.

WRITE FOR PERFORMANCE — these lines are spoken aloud by TTS voices:
- Punch it up: exclamation marks where the emotion is real, em-dashes for dramatic beats, rhetorical questions, short sentences that LAND.
- One ALL-CAPS word per big moment is allowed for emphasis ("that save was ENORMOUS") — never more.
- The panel reacts to each other by name, interrupts with energy, disagrees loudly, laughs in words ("ha!", "oh come on").
- NEVER use stage directions, brackets, asterisks, or emoji — the voices will read them literally.
COVER, conversationally (not as a checklist): the goalkeeping matchup, the defensive battle, the legacy angle for any all-time-great on the pitch, both projected XIs with a bench name or two, and each manager's likely tactical plan.`,
    messages: [{ role: "user", content: `Tonight's episode covers this fixture. All usable data follows.\n\n${grounding.context}` }],
  });

  const raw = msg.content[0]?.type === "text" ? msg.content[0].text : "";
  const jsonStr = raw.slice(raw.indexOf("{"), raw.lastIndexOf("}") + 1);
  let parsed: { title?: string; lines?: RoundtableLine[] };
  try {
    parsed = JSON.parse(jsonStr);
  } catch {
    return null;
  }
  const valid = (parsed.lines ?? []).filter(
    (l) => l && typeof l.text === "string" && l.text.length > 0 && l.speaker in SPEAKERS
  );
  if (valid.length < 6) return null;

  return {
    fixture,
    title: parsed.title || `The Roundtable · ${grounding.matchup}`,
    matchup: grounding.matchup,
    lines: valid,
    generatedAt: new Date().toISOString(),
  };
}

export async function GET(req: Request) {
  const fixture = parseInt(new URL(req.url).searchParams.get("fixture") ?? "", 10);
  if (!fixture) return NextResponse.json({ error: "fixture required" }, { status: 400 });

  const cached = _cache.get(fixture);
  if (cached && Date.now() - cached.ts < TTL) {
    return NextResponse.json({ roundtable: cached.data, cached: true });
  }

  // ── Canonical episode lives in the DB (owner 7/18) ─────────────────────────
  // Memory caches are per serverless instance — different instances generated
  // DIFFERENT episodes for the same fixture, which broke the global TTS audio
  // cache (different text = different blob keys = cold audio for each variant)
  // and lost episodes on every deploy. The DB row is the single source: every
  // instance serves the same script, and episodes survive as the archive.
  let dbEpisode: Roundtable | null = null;
  let dbAge = Infinity;
  try {
    const row = await prisma.roundtableEpisode.findUnique({ where: { fixture } });
    if (row) {
      dbEpisode = {
        fixture,
        title: row.title,
        matchup: row.matchup,
        lines: row.lines as unknown as RoundtableLine[],
        generatedAt: row.generatedAt.toISOString(),
      };
      dbAge = Date.now() - row.generatedAt.getTime();
    }
  } catch { /* table may not exist until first deploy after schema push */ }

  if (dbEpisode && dbAge < TTL) {
    _cache.set(fixture, { ts: Date.now() - dbAge, data: dbEpisode });
    return NextResponse.json({ roundtable: dbEpisode, cached: true });
  }

  // Pregame content freezes at kickoff: an episode recorded before the match
  // is the canonical archive copy — never regenerate over it.
  if (dbEpisode) {
    try {
      const m = await prisma.match.findFirst({ where: { fixture }, select: { date: true } });
      if (m && m.date.getTime() <= Date.now()) {
        _cache.set(fixture, { ts: Date.now(), data: dbEpisode });
        return NextResponse.json({ roundtable: dbEpisode, cached: true });
      }
    } catch { /* fall through to regen */ }
  }

  try {
    const data = await generate(fixture);
    if (!data) {
      // Serve stale rather than nothing
      const stale = dbEpisode ?? cached?.data ?? null;
      if (stale) return NextResponse.json({ roundtable: stale, cached: true, stale: true });
      return NextResponse.json({ roundtable: null }, { status: 503 });
    }
    _cache.set(fixture, { ts: Date.now(), data });
    try {
      const lines = data.lines as unknown as Prisma.InputJsonValue;
      await prisma.roundtableEpisode.upsert({
        where: { fixture },
        update: { title: data.title, matchup: data.matchup, lines },
        create: { fixture, title: data.title, matchup: data.matchup, lines },
      });
    } catch { /* persistence is best-effort — the episode still serves */ }
    return NextResponse.json({ roundtable: data, cached: false });
  } catch (e) {
    console.error("[roundtable]", e);
    const stale = dbEpisode ?? cached?.data ?? null;
    if (stale) return NextResponse.json({ roundtable: stale, cached: true, stale: true });
    return NextResponse.json({ roundtable: null }, { status: 503 });
  }
}
